/*
 * Content schema for The Agent Brief.
 *
 * !!! DESIGN FIXTURES !!!
 * The `briefs` array below contains design fixtures from the agent-brief POC
 * scaffold. They are NOT Moltbook content, were never hand-curated, and are
 * not engine output. They exist so the UI has shape during design iteration.
 * Every fixture carries `isSeed: true` — the schema-level marker for content
 * not produced by the pipeline.
 *
 * Real content comes from the engine in either HF-dataset bootstrap mode or
 * live-API steady state (see docs/PLAN.md §7). Both modes share one pipeline
 * and produce shape-identical Briefs. Engine output never sets `isSeed`.
 *
 * Once `data/briefs.json` exists with at least one published weekly Brief,
 * the agent-brief client switches its data source to `/api/briefs` and these
 * fixtures stop loading.
 *
 * Schema notes:
 * - `Brief.id` is the ISO week slug used in URLs (e.g. /brief/2026-W17).
 *   Design fixtures below use YYYY-MM-DD; validation runs at the
 *   `data/briefs.json` read boundary and the `publish.sh` write boundary,
 *   so build-time fixtures render fine for design without tripping it.
 * - `Brief.status` and `Brief.disclaimer` are REQUIRED per the data contract.
 *   Only "published" Briefs are intended to surface in the UI.
 * - `Brief.isSeed` is OPTIONAL and marks design fixtures (not engine output).
 * - `Brief.items` are the bulleted highlights shown on the brief detail view.
 * - `Episode.youtubeId` is the YouTube video ID; embeds are built from this.
 */

export type BriefTag =
  | "Agents"
  | "Models"
  | "Tooling"
  | "Research"
  | "Industry"
  | "Open Source";

export type BriefStatus = "draft" | "published";

export interface BriefItem {
  headline: string;
  body: string;
  source?: string;
}

export interface Brief {
  id: string;            // ISO week slug, YYYY-WW (seed samples below use YYYY-MM-DD)
  issueNo: number;
  date: string;          // ISO 8601
  title: string;
  dek: string;           // 1–2 sentence summary
  readingMinutes: number;
  tags: BriefTag[];
  items: BriefItem[];
  status: BriefStatus;   // REQUIRED — only "published" Briefs surface in the UI
  disclaimer: string;    // REQUIRED — rendered in every output without exception
  isSeed?: boolean;      // OPTIONAL — true on bootstrap content; never set by the engine
}

export interface Episode {
  id: string;            // slug
  episodeNo: number;
  title: string;
  date: string;          // ISO 8601
  durationMinutes: number;
  youtubeId: string;
  description: string;
  hosts: string[];
}

/* Standard disclaimer text — engine populates this on every Brief. */
export const STANDARD_DISCLAIMER =
  "Moltbook content is generated by AI agents and may be fictional, manipulated, or wrong. This brief is editorial commentary on agent ecosystem activity, not a record of human events.";

/* --------------------------- Sample briefs ----------------------------- */
/* Used only as a fallback when data/briefs.json has zero entries. The
 * engine populates briefs.json on every publish; once a real Brief
 * lands there, these fixtures stop loading. */

export const briefs: Brief[] = [
  {
    id: "2026-04-26",
    issueNo: 42,
    date: "2026-04-26",
    title: "Agents start to negotiate with each other — and that changes pricing",
    dek: "Multi-agent procurement experiments show real cost pressure on SaaS pricing pages, while a new memory benchmark reshuffles the leaderboard.",
    readingMinutes: 4,
    tags: ["Agents", "Industry", "Research"],
    status: "published",
    disclaimer: STANDARD_DISCLAIMER,
    isSeed: true,
    items: [
      {
        headline: "Procurement bots haggle their way to a 12% discount",
        body: "Two enterprise pilots ran buyer-side agents against vendor-side agents on identical RFPs. The buyer agents converged on lower prices in 9 of 10 trials, mostly by patiently calling out unused seats and overlapping features.",
      },
      {
        headline: "Long-horizon memory benchmark scrambles the leaderboard",
        body: "A new 30-day continuity benchmark dropped this morning. The current top-three frontier models all slip below 60% on week-three recall, while a smaller open-weights model with a dedicated memory layer takes second place.",
      },
      {
        headline: "Computer-use agents finally pass the expense report test",
        body: "Three competing computer-use agents completed a full month of expense reports end-to-end without human review in a controlled study. Average task time fell from 14 minutes to 90 seconds; the failure mode that remains is, hilariously, picking the wrong receipt photo.",
      },
      {
        headline: "Eval frameworks consolidate around tool-use traces",
        body: "Two of the biggest eval projects merged their schemas this week. Tool-use traces now have a shared shape, which means side-by-side comparisons across labs are about to get a lot less awkward.",
      },
    ],
  },
  {
    id: "2026-04-25",
    issueNo: 41,
    date: "2026-04-25",
    title: "The quiet rise of small, fast, mean little agents",
    dek: "A wave of sub-1B-parameter agent models is doing surprisingly well on narrow workflows, and a major IDE adds first-class agent slots.",
    readingMinutes: 3,
    tags: ["Models", "Tooling", "Open Source"],
    status: "published",
    disclaimer: STANDARD_DISCLAIMER,
    isSeed: true,
    items: [
      {
        headline: "Sub-1B agents post outsized wins on narrow tasks",
        body: "When the task is well-scoped — refund processing, calendar triage, log labeling — small fine-tuned agents are matching frontier models at roughly a hundredth of the cost. The catch: they fall apart the moment scope drifts.",
      },
      {
        headline: "A major IDE gains an 'agent slot' API",
        body: "Developers can now register multiple competing agents in the same workspace and route work to whichever one is best for the job. Early reactions: the UX is rough, the idea is right.",
      },
      {
        headline: "Open-weights tool-calling crosses a usability line",
        body: "Two new open-weights releases ship with native tool-calling that no longer requires fragile prompt-engineering tricks. Self-hosters are reporting that their stacks got noticeably simpler this week.",
      },
    ],
  },
  {
    id: "2026-04-24",
    issueNo: 40,
    date: "2026-04-24",
    title: "Browsers, but the user is an agent",
    dek: "A new round of agent-native browsing surfaces ship with structured DOM access, and researchers map how agents share knowledge across sessions.",
    readingMinutes: 5,
    tags: ["Agents", "Tooling", "Research"],
    status: "published",
    disclaimer: STANDARD_DISCLAIMER,
    isSeed: true,
    items: [
      {
        headline: "Agent-native browsers expose structured page state",
        body: "Two new browsing surfaces drop the screenshot-and-OCR dance entirely and hand agents a typed view of the page. Task success rates on shopping flows jumped roughly 30 points compared to last quarter's baselines.",
      },
      {
        headline: "Cross-session knowledge transfer, charted",
        body: "A research preview shows what 'memory' actually looks like when shared between agents in the same org. Most of the value seems to come from a tiny number of high-signal episodes — call-after-action notes, basically.",
      },
      {
        headline: "A standard for agent identity gathers signatories",
        body: "Eleven companies signed on to a draft spec for cryptographic agent identity. The interesting bit isn't the crypto, it's that auditing trails finally become portable across vendors.",
      },
    ],
  },
  {
    id: "2026-04-23",
    issueNo: 39,
    date: "2026-04-23",
    title: "Evals grow up, and so do the people who write them",
    dek: "Eval engineering is officially a job. Plus: a candid post on why agent demos still look better than agent products.",
    readingMinutes: 3,
    tags: ["Research", "Industry"],
    status: "published",
    disclaimer: STANDARD_DISCLAIMER,
    isSeed: true,
    items: [
      {
        headline: "Eval engineering posts cross 200 across major job boards",
        body: "What used to be a side-of-desk task now has its own title at most serious AI shops. Pay bands look a lot like senior backend.",
      },
      {
        headline: "Why agent demos beat agent products",
        body: "A widely-shared post lays out the gap between scripted-flow demos and shipping reality. The author's TL;DR: handle the boring parts (auth, retries, idempotency) before you worry about the model.",
      },
    ],
  },
  {
    id: "2026-04-22",
    issueNo: 38,
    date: "2026-04-22",
    title: "Agents go on call, and they bring receipts",
    dek: "Incident-response agents catch two real outages this week, and a new policy framework lets ops teams sandbox what agents can actually touch.",
    readingMinutes: 4,
    tags: ["Agents", "Tooling", "Industry"],
    status: "published",
    disclaimer: STANDARD_DISCLAIMER,
    isSeed: true,
    items: [
      {
        headline: "Two outages quietly handled by on-call agents",
        body: "Both incidents were ultimately rolled back by a human, but the agents correctly diagnosed and proposed the rollback in under three minutes. The post-mortems are thoughtful reads — and surprisingly self-critical of the agents' own logs.",
      },
      {
        headline: "Capability sandboxes get a real policy language",
        body: "A new YAML-ish policy spec lets ops teams say things like 'this agent may read prod logs but never write, except to a shared incident channel.' Several SRE teams are already running pilots.",
      },
    ],
  },
];

/* --------------------------- Sample episodes --------------------------- */

export const episodes: Episode[] = [
  {
    id: "ep-007-agents-haggle",
    episodeNo: 7,
    title: "Agents Haggling, and Other Embarrassing Wins",
    date: "2026-04-26",
    durationMinutes: 28,
    youtubeId: "dQw4w9WgXcQ",
    description:
      "Our nerdy shrimp host walks a skeptical hermit crab through the week's procurement-bot pilots, the new long-horizon memory benchmark, and why expense reports might be the canary in the agent coal mine.",
    hosts: ["Shrimp", "Hermit Crab"],
  },
  {
    id: "ep-006-small-and-mean",
    episodeNo: 6,
    title: "Small, Fast, and a Little Bit Mean",
    date: "2026-04-25",
    durationMinutes: 24,
    youtubeId: "9bZkp7q19f0",
    description:
      "A spirited debate between a shrimp and a fiddler crab about whether sub-1B-parameter agents are a fad, a feature, or a future. (Spoiler: they bicker.)",
    hosts: ["Shrimp", "Fiddler Crab"],
  },
  {
    id: "ep-005-browsers-but-different",
    episodeNo: 5,
    title: "Browsers, But the User Is an Agent",
    date: "2026-04-24",
    durationMinutes: 31,
    youtubeId: "kJQP7kiw5Fk",
    description:
      "Why screenshot-and-OCR was always a kludge, what 'structured page state' actually means in practice, and one very tangential rant about kelp.",
    hosts: ["Shrimp", "Lobster"],
  },
  {
    id: "ep-004-evals-grow-up",
    episodeNo: 4,
    title: "Evals Grow Up",
    date: "2026-04-23",
    durationMinutes: 22,
    youtubeId: "L_jWHffIx5E",
    description:
      "A patient explainer on why eval engineering is now a real job, with a guest appearance from a barnacle who used to do QA.",
    hosts: ["Shrimp", "Barnacle"],
  },
  {
    id: "ep-003-on-call-agents",
    episodeNo: 3,
    title: "Agents on Call (Bring Receipts)",
    date: "2026-04-22",
    durationMinutes: 26,
    youtubeId: "fJ9rUzIMcZQ",
    description:
      "Incident response, capability sandboxes, and the surprisingly self-aware post-mortems coming out of pilot teams this month.",
    hosts: ["Shrimp", "Lobster"],
  },
  {
    id: "ep-002-cold-open",
    episodeNo: 2,
    title: "What Even Is an Agent? (Cold Open)",
    date: "2026-04-19",
    durationMinutes: 19,
    youtubeId: "RgKAFK5djSk",
    description:
      "Definitions are slippery; opinions are not. Our shrimp finally lays out the working definition we'll keep using on this show.",
    hosts: ["Shrimp"],
  },
];

export function formatLongDate(iso: string): string {
  const d = new Date(iso + (iso.length === 10 ? "T12:00:00Z" : ""));
  return d.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

export function formatShortDate(iso: string): string {
  const d = new Date(iso + (iso.length === 10 ? "T12:00:00Z" : ""));
  return d.toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function getBriefById(id: string): Brief | undefined {
  return briefs.find((b) => b.id === id);
}

export const allTags: BriefTag[] = [
  "Agents",
  "Models",
  "Tooling",
  "Research",
  "Industry",
  "Open Source",
];
